### ISSUE TITLE
This is available in other languages?

### ISSUE THREAD

**Issue by anhuynh219** [openvpi/SOME#19]
Thank you for your great work!
Can this extract MIDI from singing voices in other languages? 

Thanks!

**Comment by autumn-2-net** [comment]
It might be possible, but the model is only trained on Chinese, so it might not work well in other languages.

**Comment by autumn-2-net** [comment]
And could you tell me where you found out about this program?

**Comment by anhuynh219** [comment]
I just simply look up everything related to DiffSinger everywhere. I'm currently trying to train DiffSinger in other language

**Comment by autumn-2-net** [comment]
You may have to try the language you need yourself, there is user feedback that Japanese quality is acceptable.English is not.

**Comment by anhuynh219** [comment]
Oh, I'm trying on Vietnamese. Thank you so much
