### ISSUE TITLE
Can this get the midi duration and sequence ?

### ISSUE THREAD

**Issue by francqz31** [openvpi/SOME#2]
@yqzhishen Hello it is me again I just noticed this project , like we discussed before, can this be used to get the
" MIDI sequence | MIDI duration sequence" especially for English ?

like the one in opencpop  as you said before "filename | lyrics | phoneme sequence | MIDI sequence | MIDI duration sequence | phoneme duration sequence | is slur sequence"

I'm not really looking for something to get me the "phoneme sequence  | or the phoneme duration sequence or is slur" right now,
just the Midi sequence and Midi duration sequence accurately that's what I need! so can SOME do that ?

Thanks in advance!

https://github.com/openvpi/DiffSinger/issues/29

**Comment by yqzhishen** [comment]
Yes SOME is language-independent, but you still need *.ds + *.wav to train

**Comment by yqzhishen** [comment]
At inference time SOME produces 3 outputs:
- `note_seq`, the MIDI pitch sequence
- `note_rest`, to indicate whether the note is a rest note
- `note_dur`, the MIDI duration sequence in seconds

**Comment by yqzhishen** [comment]
You can use any editors or packages that support importing/extracting MIDI file format. But if you are able to read the code, you can get the raw outputs before the MIDI file is saved in infer.py

**Comment by yqzhishen** [comment]
What are you using the MIDI file for?

Here `midis` is the raw outputs.

https://github.com/openvpi/SOME/blob/e0ca1ed9b2e71bfeb2176bc51f9fa0469f3ea0de/infer.py#L37

**Comment by yqzhishen** [comment]
[some_batch_infer.zip](https://github.com/openvpi/SOME/files/13180329/some_batch_infer.zip)

Maybe this script can help, but it is not well-documented. You need to put it in your SOME directory, edit the parameters and options in the file, and run
