### ISSUE TITLE
两个模型干啥的呢

### ISSUE THREAD

**Issue by woaiyan2222** [openvpi/SOME#6]
0917_continuous256_clean_3spk.zip)

918_continuous256_clean_3spk_fixmel.zip)
这两是什么呀
作什么用的噢O>
怎么用啊？
是要0918_continuous128_clean_3spk替换的么？
更好的？还是有针对的其他声音的模型哦？

**Comment by yqzhishen** [comment]
几个模型功能是一样的，我们也不好说哪个更好，所以全发布了，欢迎自行对比

**Comment by atomicoo** [comment]
Hi~
918_continuous256_clean_3spk_fixmel 与 0917_continuous256_clean_3spk 的具体区别是？模型结构？或者训练数据？

**Comment by autumn-2-net** [comment]
> Hi~ @yqzhishen 
> 918_continuous256_clean_3spk_fixmel 与 0917_continuous256_clean_3spk 的具体区别是？模型结构？或者训练数据？

没有fixmel的 是mel参数写错了  导致在数据增强之后的mel是缺频单的

**Comment by atomicoo** [comment]
@autumn-2-net Thx~
方便问下这两个模型大概用了多大数据量进行训练吗？
