### ISSUE TITLE
我能用自己的数据训练这模型吗

### ISSUE THREAD

**Issue by rainbowjack** [openvpi/SOME#9]
如果能我该输入啥命令呢，找了半天都没找到比如path_of_dataset这种东西

**Comment by yqzhishen** [comment]
目前需要使用DiffSinger数据集标注中的.ds文件进行训练，其他配置方法看代码和配置文件就行，训练和预处理代码还没妥善整理过

**Comment by rainbowjack** [comment]
emmm谢谢，看来作为初学者每天还得去看看diffsinger是个啥

**Comment by yqzhishen** [comment]
预处理binarize.py， 训练train.py，配置文件基本和diffsinger长得一样的，raw_data_dir是原始数据集，binary_data_dir是处理后数据集，数据集里面的.ds文件就note_seq, note_dur, note_slur三个key，放置方式和diffsinger也是一样的，其他的就结合代码和diffsinger的文档看吧

**Comment by rainbowjack** [comment]
ok感谢，明天我努力读懂试试看，不过可能还会有不少疑问（挠头）

**Comment by zzzengzhe** [comment]
> 目前需要使用DiffSinger数据集标注中的.ds文件进行训练，其他配置方法看代码和配置文件就行，训练和预处理代码还没妥善整理过

配置文件能提供一下吗？我从Diffsinger上复制了配置文件进行修改，但是改了好久就没成功，谢谢！
